[package]
name = "network_flow-minimum_cost_flow-cost_scaling_push_relabel"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
name = "cost_scaling_push_relabel"

[dependencies]
num = "0.3.0"
num-traits = "0.2.12"
